[package]
name = "lalrpop-calculator"
version = "0.1.0"
authors = ["Nakayama Daiju"]
edition = "2018"

[build-dependencies]
lalrpop = { version = "0.19", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19"
regex = "1"
